version: "2.2"

services:
  app:
    build: ./app
    ports:
      - "5005:5005"
    depends_on:
      - database

  database:
    build: ./database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db

  webserver:
    build: ./webserver
    ports:
      - "8088:8088"
    depends_on:
      - app
