version: "2.2"

services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    networks:
      my_network:
        ipv4_address: 172.25.0.2

  database:
    build: ./database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db

  webserver:
    build: ./webserver
    ports:
      - "8088:8088"
    depends_on:
      - app
    environment:
      APP_CONTAINER_IP: 172.25.0.2

networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
